elastic/crd-ref-docs

README.md, processor/processor.go, templates/asciidoctor/type.tpl, types/types.go
Sorts the references of a type so that the generated documentation remains stable between runs.
=> Sort references

processor/processor.go, test/api/v1/guestbook_types.go, test/expected.asciidoc
Comments attached to basic type aliases were missing because the code returned too early from the loop.
Thanks to @hugoShaka for finding the problem and suggesting a fix.
Fixes #7
=> Do not ignore basic type comments

.gitignore, README.md, config.yaml, main.go, renderer/asciidoctor.go, renderer/markdown.go, renderer/renderer.go, templates/markdown/gv_details.tpl, templates/markdown/gv_list.tpl, templates/markdown/type.tpl, templates/markdown/type_members.tpl, templates/templates.go, test.sh, test/expected.asciidoc, test/expected.md
* Add renderer for Markdown
* Add templates for Markdown
* Add Markdown tests to test.sh
=> Add support for Markdown

processor/processor.go, test/expected.asciidoc, test/expected.md, types/types.go
Closes https://github.com/elastic/crd-ref-docs/issues/20
Checks if the type is array, slice, or pointer, even though the type name is already known.
Is therefore able to return `[]Foo`, instead of simply returning `Foo`, when `Foo` is already known.
=> Fix array/slice/pointer type for custom types

renderer/asciidoctor.go, templates/asciidoctor/type_members.tpl, test/api/v1/guestbook_types.go, test/expected.asciidoc, test/expected.md
* Provides a function to escape the pipe character, which has special meaning for asciidoc as a way to format tables, so that including | in a comment does not result in wonky tables.
* Wrap type_members in the new escape function
This does not include:
* changes to the markdown renderer (since escaping could be flavor-specific. For example GFM would use `\|` but other flavors could use `&#124;`).
* Escaping other characters, although that could be added.
For context, my team uses crd-ref-docs, and it has worked great for the most part. However we want to describe an LDAP query with a pipe character in a comment, but this led to the API docs showing a table that didn't render correctly. See [here](https://github.com/vmware-tanzu/pinniped/blob/main/generated/1.20/README.adoc#k8s-api-go-pinn …
=> Escape pipe characters in asciidoc descriptions

test.sh, test/config.yaml, test/expected.asciidoc, test/expected.md
I think the tests should use the test config, so that the config is part of the tests.
=> Use test config in tests

config/config.go, processor/config.go, processor/processor.go
=> feat: allow using raw docstring for type docs

test/api/v1/guestbook_types.go
The changes in https://github.com/elastic/crd-ref-docs/pull/25 does not follow gofmt, this PR fixes that.
=> refactor: fix formatting in test types

processor/processor.go, test/api/v1/guestbook_types.go, test/expected.asciidoc, test/expected.md, types/types.go
=> Make inlined structs get references from where they are inlined

processor/processor.go, test/api/v1/guestbook_types.go
Standalone types was previously only parsed correctly if part of a struct, and parsed as a struct field.
Without the processor change, moving `Rating` to the top causes the following diff:
```
ERROR: outputs differ
| *`rating`* __xref:{anchor_prefix}-github-com-elastic-crd-re | | *`rating`* __Rating__ | Rating provided by the guest
<
<
<
[id="{anchor_prefix}-github-com-elastic-crd-ref-docs-api-v1-r <
==== Rating (string)                                          <
<
Rating is the rating provided by a guest.                     <
<
.Appears In:                                                  <
****                                                          <
- xref:{anchor_prefix}-github-com-elastic-crd-ref-docs-api-v1 <
****                                                          <
```
=> fix: parse standalone types correctly

go.mod
Missing from https://github.com/elastic/crd-ref-docs/pull/42 ?
=> chore: update go mod version to 1.20

processor/processor.go
So that `p.parser.LookupType(tPkg, typeDef.Name)` in `loadAliasType` uses the same collector as everywhere else
=> fix: use single parser collector

processor/processor.go, renderer/asciidoctor.go, renderer/functions.go, renderer/markdown.go, templates/asciidoctor/type.tpl, templates/markdown/type.tpl, test/api/v1/guestbook_types.go, test/expected.asciidoc, test/expected.md, types/types.go
Simplifies a lot of the complexity of having separate `processType`, `loadType` and `loadAliasType`.
Removes ArrayKind, as it is not supported by controller-gen.
Also ensures correct parsing of `A` in the example below, making `A.UnderlyingType` equal `B` instead of `string`. This will be required to correctly parse and propagate markers (https://github.com/elastic/crd-ref-docs/pull/49).
```go
type Foo struct {
A A `json:"a,omitempty"`
}
type A B
type B string
```
=> feat: improve parsing

renderer/asciidoctor.go, renderer/markdown.go, templates/markdown/type_members.tpl, test/api/v1/guestbook_types.go, test/expected.asciidoc, test/expected.md
If an API type field comment is multi-line, it breaks rendering both Markdown and Asiidoc tables. This PR aims to fix this issue by:
- turning newlines into two break lines (`<br />`) HTML elements in Markdown renderer, 
- turning newlines into hard break lines in Asiidoc renderer.
Should fix https://github.com/elastic/crd-ref-docs/issues/52.
=> fix: handle fields' multi-line comments

main.go
When migrating to `v0.0.10`, we had to bump our max depth.
I think https://github.com/elastic/crd-ref-docs/pull/51 introduced some new layers in parsing, and that the default depth should therefore be bumped a bit.
=> chore: increase default max depth

renderer/asciidoctor.go, renderer/asciidoctor_test.go, renderer/markdown.go, templates/asciidoctor/type.tpl, test/api/v1/guestbook_types.go, test/expected.asciidoc, test/expected.md
Resolves https://github.com/elastic/crd-ref-docs/issues/61
Looks good in https://github.com/elastic/crd-ref-docs/blob/379dc3b3120b5b7cd8850cb89f99f85a458dfe09/test/expected.asciidoc#guestbookentry
=> fix: escape asterix in adoc

test/api/common/common.go, test/api/common/groupversion_info.go, test/api/v1/guestbook_types.go, test/expected.asciidoc, test/expected.md
The test should probably have multiple packages, to assert that references across packages are displayed correctly in doc.
Relates to https://github.com/elastic/crd-ref-docs/issues/58
=> test: common api package

README.md
Sorry for missing the README.md update about the output mode changes in my last pull request, this new pull request fixes it.
=> Add output mode in README.md

README.md, config/config.go, processor/config.go, processor/processor.go, test.sh, test/api/v1/guestbook_types.go, test/config.yaml, test/hide.md, test/templates/markdown/gv_details.tpl, test/templates/markdown/gv_list.tpl, test/templates/markdown/type.tpl, test/templates/markdown/type_members.tpl
fix: https://github.com/elastic/crd-ref-docs/issues/70
=> Support custom markers

renderer/markdown.go
`markdownRenderFieldDoc`  should espace `{` and `}`.
=> fix: escape curly brakets for markdown

templates/markdown/type.tpl, test/api/v1/guestbook_types.go, test/expected.asciidoc, test/expected.md, test/hide.md, test/templates/markdown/type.tpl
Validation pattern is not currently markdown escaped and can break markdown's table markup when it includes a `|` character
=> fix validation regex containing pipe character breaks default markdown template table

main.go
Previously, the code returned exit code 0 even when the template generation failed. Now, if an error occurs, the program will return exit code 1.
Additionally, silence errors from cobra execution. Previously, Cobra was printing non-formatted errors. However, we already log these errors via zap. This fix silences Cobra from printing redundant logs.
=> Return Exit Code 1 on Failure

templates/markdown/type.tpl, test/expected.md
Update the enum table in the `type.tpl` template to include missing table header, ensuring it renders correctly as a markdown table.
=> Fix missing markdown table formatting

.github/workflows/release.yml, main.go
This makes the `version` command also works when the binary is installed using `go install`.
Follow-up of #78 and #84.
=> Also support version on go install

processor/processor.go
I spent the whole afternoon trying to figure out what the problem was, this's an important log, should live in warn level.
=> change log level to warn when maxDepth exceed

README.md, processor/processor.go, test/api/common/groupversion_info.go, test/config.yaml, test/hide.md, test/templates/markdown/gv_details.tpl, types/types.go
This starts propagating package-level markers so they can be used in templates if desired (similar to field and type-level markers).
=> feat: allow using custom markers on pkg level

renderer/asciidoctor.go, renderer/asciidoctor_test.go, test/api/v1/guestbook_types.go, test/expected.asciidoc, test/expected.md, test/hide.md
Asciidoc interprets curly braces as an identifier. Kubebuilder validations may contain curly braces as part of a regular expression pattern. This adds an escape character to the leading curly brace when rendering validation content for `asciidoctor`. Per documentation [1], this is sufficient to prevent id attribute interpretation.
This change does not broadly add escape characters to all curly braces used in CRD godoc text. This risks breaking teams that have embedded asciidoc within their code comments - for example, to provide links or other cross-references.
Fixes #137
[1] https://docs.asciidoctor.org/asciidoc/latest/subs/prevent/#escape-with-backslashes
=> Escape curly braces in validation text for `asciidoc`

.goreleaser.yaml
Released binaries for `linux/amd64` are dynamically linked, which makes them difficult to use in Alpine. Since we don't need to use anything related to CGO, we can simply disable it and it resolves the issue as it then produces a static build for native platforms. (Tested under `linux/arm64`, but the principle is the same.)
```
root@3b09588545ab:/app# ./bin/usr/bin/goreleaser build --auto-snapshot --clean
• git repository is dirty and --auto-snapshot is set, implying --snapshot
(...)
• building binaries
(...)
• building                                       binary=dist/crd-ref-docs_linux_arm64_v8.0/crd-ref-docs
• building                                       binary=dist/crd-ref-docs_linux_amd64_v1/crd-ref-docs
• writing artifacts metadata
• build succeeded after 2s
• thanks for using …
```
=> Disable CGO in GoReleaser

.gitignore, config/config.go, config/kv.go, main.go, renderer/asciidoctor.go, renderer/markdown.go, renderer/markdown_test.go, test.sh, test/hide.md, test/templates/markdown/gv_list.tpl
Similar to https://github.com/elastic/go-licence-detector/pull/29:
```
./crd-ref-docs --template-value=k1=v1
```
```md
Here is a value: {{ markdownTemplateValue "k1" }}
```
So I think I'm going to do the same in https://github.com/elastic/go-licence-detector/pull/29 for consistency.
=> Allow additional template variables
